/*
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 *     http://duracloud.org/license/
 */
package org.duracloud.ldap.domain;

import java.util.Set;

/**
 * Note: This class is a proper subset of the class of the same name in
 * Management Console baseline.
 * TODO: Refactor
 *
 * @author Andrew Woods
 *         Date: 1/3/13
 */
public class AccountRights extends BaseDomainData {

    private int accountId;
    private int userId;
    private Set<Role> roles;

    public AccountRights(int id, int accountId, int userId, Set<Role> roles) {
        this.id = id;
        this.accountId = accountId;
        this.userId = userId;
        this.roles = roles;
    }

    public int getAccountId() {
        return accountId;
    }

    public int getUserId() {
        return userId;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    /*
    * Generated by IntelliJ
    */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        AccountRights that = (AccountRights) o;

        if (accountId != that.accountId) {
            return false;
        }
        if (userId != that.userId) {
            return false;
        }
        if (roles != null ? !roles.equals(that.roles) : that.roles != null) {
            return false;
        }

        return true;
    }

    /*
    * Generated by IntelliJ
    */
    @Override
    public int hashCode() {
        int result = accountId;
        result = 31 * result + userId;
        result = 31 * result + (roles != null ? roles.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(accountId);
        sb.append(":");
        sb.append(userId);
        sb.append(":");
        sb.append(roles);
        return sb.toString();
    }

}
