/*
 * The contents of this file are subject to the license and copyright
 * detailed in the LICENSE and NOTICE files at the root of the source
 * tree and available online at
 *
 *     http://duracloud.org/license/
 */
package org.duracloud.ldap.domain;

import org.apache.commons.lang.StringUtils;

import java.util.HashSet;
import java.util.Set;

/**
 * Note: This class is a proper subset of the class of the same name in
 * Management Console baseline.
 * TODO: Refactor
 *
 * @author Andrew Woods
 *         Date: 1/3/13
 */
public class DuracloudGroup extends BaseDomainData implements Comparable<DuracloudGroup> {

    public static final String PREFIX = "group-";
    public static final String PUBLIC_GROUP_NAME = PREFIX + "public";
    /**
     * Group names must begin with PREFIX.
     */
    private String name;
    private Set<Integer> userIds;
    private int accountId;

    public DuracloudGroup(int id, String name, int accountId) {
        this(id, name, accountId, null);
    }

    public DuracloudGroup(int id,
                          String name,
                          int accountId,
                          Set<Integer> userIds) {
        if (StringUtils.isBlank(name) || !name.startsWith(PREFIX)) {
            throw new IllegalArgumentException(
                "Name arg must begin with " + PREFIX + ", " + name);
        }

        this.id = id;
        this.name = name;
        this.accountId = accountId;
        this.userIds = userIds;
    }

    public String getName() {
        return this.name;
    }

    public String getDisplayName() {
        return this.name.replaceFirst(PREFIX, "");
    }

    /**
     * This method returns the ids of the users belonging to this group.
     *
     * @return ids of users of this group or an empty set
     */
    public Set<Integer> getUserIds() {
        if (null == userIds) {
            userIds = new HashSet<Integer>();
        }
        return userIds;
    }

    public void setUserIds(Set<Integer> userIds) {
        this.userIds = userIds;
    }

    public void addUserId(Integer userId) {
        getUserIds().add(userId);
    }

    public boolean removeUserId(Integer userId) {
        return getUserIds().remove(userId);
    }

    public int getAccountId() {
        return accountId;
    }

    /*
    * Generated by IntelliJ
    */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        DuracloudGroup that = (DuracloudGroup) o;

        if (accountId != that.accountId) {
            return false;
        }
        if (name != null ? !name.equals(that.name) : that.name != null) {
            return false;
        }
        if (userIds != null ? !userIds.equals(that.userIds) :
            that.userIds != null) {
            return false;
        }

        return true;
    }

    /*
    * Generated by IntelliJ
    */
    @Override
    public int hashCode() {
        int result = name != null ? name.hashCode() : 0;
        result = 31 * result + (userIds != null ? userIds.hashCode() : 0);
        result = 31 * result + accountId;
        return result;
    }

    @Override
    public int compareTo(DuracloudGroup o) {
        return o.name.compareTo(this.name);
    }

}
